fout = assert(io.open('ceu','w'))
fin  = assert(io.open'ceu.lua'):read'*a'

function subst (name)
    local s, e = string.find(fin, "dofile '"..name.."'")
    fin = string.sub(fin, 1, (s-1))
            .. assert(io.open(name)):read'*a' ..
          string.sub(fin, (e+1))
end

subst 'lines.lua'
subst 'parser.lua'
subst 'ast.lua'
subst 'env.lua'
subst 'props.lua'
subst 'tight.lua'
subst 'exps.lua'
subst 'async.lua'
subst 'gates.lua'
subst 'nfa.lua'
subst 'dfa.lua'
subst 'graphviz.lua'
subst 'code.lua'

-- template.c, binheap.[hc]
do
    local tpl = assert(io.open'template.c'):read'*a'

    local s, e = string.find(tpl, '#include "binheap.h"')
    tpl = string.sub(tpl, 1, (s-1))
            .. assert(io.open'binheap.h'):read'*a' ..
          string.sub(tpl, (e+1))

    local s, e = string.find(tpl, '#include "binheap.c"')
    tpl = string.sub(tpl, 1, (s-1))
            .. assert(io.open'binheap.c'):read'*a' ..
          string.sub(tpl, (e+1))

    local s, e = string.find(fin, "assert%(io%.open'template%.c'%):read'%*a'")
    fin = string.sub(fin, 1, (s-1))
            .. "[===[" .. tpl .. "]===]" ..
          string.sub(fin, (e+1))
end

fout:write([=[
#!/usr/bin/env lua

--[[
-- This file is automatically generated.
-- Check the github repository for a readable version:
-- http://github.com/fsantanna/ceu
--]]

]=] .. fin)

fout:close()
