optparse = dofile 'optparse.lua'

dofile 'dbg.lua'    ; DBG,ASR = DBG1,ASR1
dofile 'cmd.lua'
dofile 'pre.lua'    ; DBG,ASR = DBG2,ASR2
dofile 'lines.lua'
dofile 'parser.lua'
dofile 'ast.lua'
dofile 'adjs.lua'
dofile 'types.lua'
dofile 'dcls.lua'
dofile 'names.lua'
dofile 'exps.lua'
dofile 'consts.lua'
dofile 'stmts.lua'
dofile 'inits.lua'
dofile 'scopes.lua' ; DBG,ASR = DBG1,ASR1
--AST.dump(AST.root)

--ceu
if CEU.opts.ceu then
    local function SUB (str, from, to)
        assert(to, from)
        local i,e = string.find(str, from, 1, true)
        if i then
            return SUB(string.sub(str,1,i-1) .. to .. string.sub(str,e+1),
                       from, to)
        else
            return str
        end
    end

    local H = ASR(io.open(CEU.opts.ceu_output_h,'w'))
    local C = ASR(io.open(CEU.opts.ceu_output_c,'w'))

    -- CEU_SYS.H
    C:write('\n\n/* CEU_SYS_H */\n\n'..PAK.files.ceu_sys_h)

    -- CEU_SYS.C
    C:write('\n\n/* CEU_SYS_C */\n\n'..PAK.files.ceu_sys_c)

    H:close()
    C:close()
end

--env
if CEU.opts.env then
    local c = ''

    --env-header
    do
        local f = ASR(io.open(CEU.opts.env_header))
        c = c..'\n\n/* ENV_HEADER */\n\n'..f:read'*a'
        f:close()
    end

    --env-ceu
    do
        local f = ASR(io.open(CEU.opts.env_ceu))
        c = c..'\n\n/* ENV_CEU */\n\n'..f:read'*a'
        f:close()
    end

    --env-main
    do
        local f = ASR(io.open(CEU.opts.env_main))
        c = c..'\n\n/* ENV_MAIN */\n\n'..f:read'*a'
        f:close()
    end

    --env-output
    do
        local f = ASR(io.open(CEU.opts.env_output,'w'))
        f:write([[
/*
 * This file is automatically generated.
 * http://www.ceu-lang.org/
 * http://github.com/fsantanna/ceu/
 *
 * Céu is distributed under the MIT License:
 *

Copyright (C) 2012-2016 Francisco Sant'Anna

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

]] .. c)
        f:close()
    end
end

--cc
if CEU.opts.cc then
    local cc = CEU.opts.cc_exe..' '..CEU.opts.cc_input..' '..
                '-o '..CEU.opts.cc_output..' '..
                CEU.opts.cc_args
    os.execute(cc)
end
